name: Fetch TLE

on:
  schedule:
    - cron: '45 4,12,20 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"
          cache: "pip"

      - run: pip install -r requirements.txt

      - run: python script.py

      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add starlink_tle_history.csv
          git diff --staged --quiet || git commit -m "Update TLE data"
          git push
